#!/bin/bash
#                         License
#
# Copyright (C) 2021  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
#
# specjbb-run script automates the specjbb-run based on system size.  It does not
# include the actual specjbb kit, that is left to the end user to provide.
#
# Defined options
#
script_dir=$(realpath $(dirname $0))
act_jvms=0
java_version=21
RESULTSDIR_TOP=""
rtc=0
arguments="$@"
test_name="specjbb"
version="1.0"
declare -a nodes
nodes_count=0
ramp_up=60
runtime=120
measurement=60
node_pinning="n"
node_list="1,node"
nr_jvms=0
config="none"
specjbb_opts="none"
execname=$0
regression=0
specjbb_kit=""
java_exec="/bin/java"
test_status="Ran"
start_warehouse=0
increment_warehouse=0
pdir=""
save_csv_file=""

tools_git=https://github.com/redhat-performance/test_tools-wrappers

#
# Archive any old runs.
#
ls /tmp/results*specjbb* &> /dev/null
if [[ $? -eq 0 ]]; then
	pushd /tmp > /dev/null

	timestamp=`date | sed "s/ /_/g"`
	arch_dir="specjbb_archive/${timestamp}"
	mkdir -p $arch_dir
	mv results*_specjbb* $arch_dir
	mv specjbb*out $arch_dir
	popd >& /dev/null
fi


if [ ! -f "/tmp/${test_name}.out" ]; then
	command="${0} $@"
	echo $command
	$command &> /tmp/${test_name}.out
	rtc=$?
	if [[ -f /tmp/${test_name}.out ]]; then
		cat /tmp/${test_name}.out
		rm /tmp/${test_name}.out
	fi
	exit $rtc
fi

#
# Get the directory were the command lives.
#
curdir=`pwd`
if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi

error_out()
{
	echo $1
	exit $2
}

#
# For runs with multiple JVMs, we need to sum everything up.  Note,
# this includes the WH count, as each JVM is running (Total WH)/# JVMs.
#
present_wh_results()
{
	in_file=${1}
	csv_file=${2}
	jvms=${3}
	start_time=${4}
	end_time=${5}
	last_wh=0
	total_wh=0
	total_bops=0
	while IFS= read -r data_in
	do
		wh=`echo $data_in | cut -d':' -f 1`
		val=`echo $data_in | cut -d':' -f 2`
		#
		# If first time through the loop, set the initial values.
		#
		if [ $last_wh -eq 0 ]; then
			total_bops=$val
			total_wh=$wh
			last_wh=$wh
			continue
		fi
		#
		# We are on to the next WH count, report what we have summed up,
		# and reset the values.
		#
		if [ $last_wh -ne $wh ]; then
			if [[ $to_use_pcp -eq 1 ]]; then
				results2pcp_add_value "Warehouse:${total_wh}"
				results2pcp_add_value "BOPs:${total_bops}"
				results2pcp_add_value "JVMs:${jvms}"
				if [[ $node_pinning == "y" ]]; then
					results2pcp_add_value "Numa_bound:1"
				else
					results2pcp_add_value "Numa_bound:0"
				fi
				results2pcp_add_value_commit
				#
				# To prevent WH confusion, reset. Do not reset iterations
				#
				reset_pcp_om
			fi
			data_string=$(build_data_string "$total_wh" "$total_bops" "$jvms" "${start_time}" "${end_time}")
			echo $data_string >> $csv_file
			total_bops=$val
			total_wh=$wh
			last_wh=$wh
			continue
		fi
		#
		# Warehouses is the same as the prior Warehouses, sum up the # Warehouses, and the total bops done.
		#
		let "total_wh=$total_wh+$wh"
		let "total_bops=$total_bops+$val"
	done < "${in_file}"
	#
	# Do not forget the last Warehouse count.
	#
	data_string=$(build_data_string "$total_wh" "$total_bops" "$jvms" "${start_time}" "${end_time}")
	echo $data_string >> $csv_file
	if [[ $to_use_pcp -eq 1 ]]; then
		results2pcp_add_value "Warehouse:${total_wh}"
		results2pcp_add_value "BOPs:${total_bops}"
		results2pcp_add_value "JVMs:${act_jvms}"
		results2pcp_add_value_commit
		if [[ $node_pinning == "y" ]]; then
			results2pcp_add_value "Numa_bound:1"
		else
			results2pcp_add_value "Numa_bound:0"
		fi
		#
		# To prevent WH confusion, reset. Do not reset iterations
		#
		reset_pcp_om
	fi
}

#
# Reduce the data.  We take the max for each warehouse
#
process_specjbb_data()
{
	start_time=${1}
	slart_time=${2}
	total_data=$(mktemp /tmp/specjbb_data.XXXXXX)
	#
	# Locate the last created specjbb results
	#
	rdir=`ls -td results_*specjbb* | grep -v tar | grep -v zip | tail -1`
	pushd $rdir > /dev/null
	#
	# Look up based on the $node_jvms ran with.  We list by time, filter out tar and
	# zip files.  The last item in the list will be the latest run.
	#
	lvl1=`ls -td results_*specjbb*${node_jvms}* | grep -v tar | grep -v zip | tail -1`
	for lvl2 in `ls -d $lvl1/results_specjbb*`; do
		pushd $lvl2 > /tmp/null
		csv_file=`pwd`/results_${test_name}.csv
		save_csv_file=$csv_file
		if [ ! -f $csv_file ]; then
			$TOOLS_BIN/test_header_info --front_matter --results_file $csv_file --host $to_configuration --sys_type $to_sys_type --tuned $to_tuned_setting --results_version $version --test_name $test_name --field_header "Warehouses,Bops,Numb_JVMs"
		fi
		for dir_work in `ls -d SPEC*`; do
			pushd $dir_work > /dev/null
			processed=0

			rm -f $total_data*
			#
			# Verify we have a SPEC*txt file.
			#
			ls SPEC*txt &> /dev/null
			if [[ $? -ne 0 ]]; then
				popd > /dev/null
				continue
			fi

			#
			# Go through each results file and pull the warehouse results.
			# Afterwards we will organize the data.
			#
			for file_in in `ls SPEC*txt`; do
				wh_found=0
				cat $file_in | sed "s/[*]/ /g" > ${file_in}.out
				while IFS= read -r data_in
				do
					#
					# Keep reading until Warehouses is hit.  Then keep
					# going until the new line is hit.
					#
					if [[ ${data_in} == *"Warehouses"* ]]; then
						wh_found=1;
						continue
					fi
					if [ $wh_found -eq 0 ]; then
						continue
					fi
					cline=`echo $data_in | sed "s/^ //"`
					if [[ $cline == "" ]]; then
						break
					fi
					echo $cline | sed "s/ /:/g" >>  $total_data
				done < "${file_in}.out"
			done
			if [[ -f $total_data ]]; then
				#
				# Sort the data by Warehouses.  Once done call present_wh_results
				# to sum the run up.
				#
				sort -n $total_data > ${total_data}_sorted
				present_wh_results ${total_data}_sorted $csv_file $node_jvms ${start_time} ${end_time}
				rm ${total_data}*
				popd > /dev/null
			fi
		done
		lines=`wc -l $csv_file | cut -d' ' -f 1`
		if [ $lines -lt 2 ]; then
			test_status="Failed"
		fi
		popd > /dev/null
	done
	popd  > /dev/null
}

#
# Populate the property file with the appropriate information.
#
set_prop_file()
{
	tmp_file1=$(mktemp /tmp/specjbb_temp.XXXXXX)
	tmp_file2=$(mktemp /tmp/specjbb_temp.XXXXXX)
	#
	# syntax of $1
	# ENDWH=<val>:STARTWH=<val> and so forth.
	#
	if [[ $1 != "none" ]]; then
		config=`echo $1 | cut -d: -f 1`
		config_list=`echo $1 | cut -d: -f 2-1000`
		work_with=`echo $config_list | sed "s/:/ /g"`
		for i in $work_with; do
			field=`echo $i | cut -d'=' -f 1`
			value=`echo $i | cut -d'=' -f 2`

			if [[ $field == "ENDWH" ]]; then
				end_warehouse=$value
				continue
			fi
			if [[ $field == "INCWH" ]]; then
				increment_warehouse=$value
				continue
			fi
			if [[ $field == "STARTWH" ]]; then
				start_warehouse=$value
				continue
			fi
			if [[ $field == "RAMPUP_TIME" ]]; then
				ramp_up=$value
				continue
			fi
			if [[ $field == "MEASURE_TIME" ]]; then
				measurement=$value
				continue
			fi
		done
	fi
	if [ $regression -eq 1 ]; then
		measurement=120
		increment_by=`echo "${end_warehouse}/8" | bc`
		increment_warehouse=$increment_by
	fi
	#
	# Calculate ending warehouse, increment warehouses and starting warehouse
	# based on the number of jvms doing.
	#
	ewh=`echo ${end_warehouse}/${node_jvms} | bc`
	iwh=`echo ${increment_warehouse}/${node_jvms} | bc`
	swh=`echo ${start_warehouse}/${node_jvms} | bc`
	sed "s/input.ramp_up_seconds=30/input.ramp_up_seconds=${ramp_up}/g" $run_dir/SPECjbb.props > $tmp_file1
	sed "s/input.measurement_seconds=240/input.measurement_seconds=${measurement}/g" $tmp_file1 > $tmp_file2
	sed "s/#input.ending_number_warehouses=2/input.ending_number_warehouses=${ewh}/g" $tmp_file2 > $tmp_file1
	sed "s/input.starting_number_warehouses=1/input.starting_number_warehouses=${swh}/g" $tmp_file1 > $tmp_file2
	sed "s/input.output_directory=results/input.output_directory=results_specjbb/g" $tmp_file2 > $tmp_file1
	if [[ $node_jvm -gt 1 ]]; then
		sed "s/input.jvm_instances=1/input.jvm_instances=${node_jvms}/g" $tmp_file1 > $tmp_file2
		sed "s/input.increment_number_warehouses=1/input.increment_number_warehouses=${iwh}/g" $tmp_file2 > $run_dir/prop.file
	else
		sed "s/input.increment_number_warehouses=1/input.increment_number_warehouses=${iwh}/g" $tmp_file1 > $run_dir/prop.file
	fi
	rm -f $tmp_file1 $tmp_file2
}

#
# Obtain node information
#
obtain_nodes()
{
	curdir=`pwd`
	for i in ` ls -d /sys/devices/system/node/node*`; do
		cd $i
		cpu_list=""
		seper=""
		for j in `ls -d cpu* | grep -v map | grep -v list | sed "s/cpu//"`; do
			cpu_list=${cpu_list}${seper}${j}
			seper=','
		done
		nodes[$nodes_count]=$cpu_list
		let "nodes_count=$nodes_count+1"
	done

	let "nodes_count=$nodes_count-1"
	cd $curdir
}

#
# Group the output files
#
concat_files()
{
	for njobs  in 0 `seq 1 1 $1`; do
		if [[ -f /tmp/${test_name}_${to_tuned_setting}_job_${njobs}.out ]]; then
			cat /tmp/${test_name}_${to_tuned_setting}_job_${njobs}.out >> /tmp/${test_name}_${to_tuned_setting}.out
			cp /tmp/${test_name}_${to_tuned_setting}.out /tmp/${test_name}.out
		fi
	done
}

#
# Execute specjbb.  Passed in is
#  syntax of $1
#  ENDWH=<val>:STARTWH=<val> and so forth.
#
execute_specjbb()
{
	prop_opts=$1
	set_prop_file $prop_opts

	# start the controller
	if [[ $node_jvms -gt 1 ]]; then
		specjbb2005_dir=${run_dir}/SPECjbb2005
		specjbb_cp="${specjbb2005_dir}/jbb.jar:${specjbb2005_dir}/check.jar"
		java_opts=
		java -cp ${specjbb_cp} -Xms32m -Xmx32m ${java_opts} spec.jbb.Controller -propfile ${run_dir}/prop.file &
		controller_pid=$!
		if [ "x$controller_pid" = "x" ]; then
			printf "\t${benchmark}: unable to start the java controller\n\n"
			exit 1
		fi
		#
		# Give it a chance to come up.
		#
		sleep 5
	fi
	#
	# Note: Assumption here.  The more CPUs we have in the system the more memory we have
	#       in the system.
	#
	# We need to increase the stack size every 256 cpus  The smaller stack size
	# will cause specjbb to terminate early.  We do not want to simply use a larger stack size
	# as it will cause issues with limited memory systems.
	#
	base_stack=8192
	
	let "act_jvms=$nr_jvms+1"
	stack_size=`echo "(1+(($wcpus/256)/$act_jvms))*${base_stack}" | bc`

	#
	# Start up all the jvms.
	#
	bind_cmd=""
	if [[ $to_use_pcp -eq 1 ]]; then
		start_pcp_subset
	fi
	for jvms in 0 `seq 1 1  $nr_jvms`; do
		let "pass_jvm=$jvms+1"
		if [[ $node_pinning == "y" ]]; then
			bind_cmd="numactl  --membind  $jvms --cpunodebind $jvms"
		fi
		$bind_cmd ./run.sh --java_exec $java_exec --jvm_number $pass_jvm --stack_size $stack_size --total_jvms $act_jvms >> /tmp/${test_name}_${to_tuned_setting}_job_${pass_jvms}.out &
		#
		# Save the pid for later waiting.
		#
		pids[${pindex}]=$!
		let "pindex=$pindex+1"
	done
	#
	# Wait for every one to finish.
	#
	for pid in ${pids[*]}; do
		wait $pid
		if [ $? -ne 0 ]; then
			rtc=1
		fi
	done

	if [[ $node_jvms -gt 1 ]]; then
		kill $controller_pid > /dev/null 2>&1
		wait $controller_pid
	fi
	if [ $rtc -ne 0 ]; then
		echo "One or more specjbb jobs failed"
	fi
	concat_files $nr_jvms
}

#
# Run the specjbb benchmark
#
run_specjbb()
{
	declare -a pids
	pindex=0

	#
	# Prepare things for execution.
	#
	cp $run_dir/specjbb_extra/run.sh $run_dir
	cd $run_dir

	#
	# Prepare things for execution.
	#
	file=`/$to_home_root/$to_user/tools_bin/get_params_file -d /$to_home_root/$to_user -c ${to_sysname} -t ${test_name}`
	# Arrays are 0 based
	let nr_jvms="$nr_jvms-1"


	for iterations  in 1 `seq 2 1 $to_times_to_run`; do
		pindex=0
		if [[ $to_use_pcp -eq 1 ]]; then
			start_pcp_subset
		fi

		if test -f "$file"; then
			while IFS= read -r specjbb_opts
			do
				execute_specjbb $specjbb_opts
			done < "$file"
		else
			start_time=$(retrieve_time_stamp)
			execute_specjbb $specjbb_opts
			end_time=$(retrieve_time_stamp)
		fi

		#
		# We need to process the data
		#
		pushd /tmp > /dev/null
		if [[ $RESULTSDIR_TOP == "" ]]; then
			RESULTSDIR_TOP=results_${test_name}_${tuned_setting}_$(date "+%Y.%m.%d-%H.%M.%S")
		fi
		RESULTSDIR=${RESULTSDIR_TOP}/results_${test_name}_${to_tuned_setting}_${node_jvms}_results
		# We do not want any old data.
		#
		mkdir -p ${RESULTSDIR}
		if [[ -d results_${test_name}_${to_tuned_setting} ]]; then
			mv results_${test_name}_${to_tuned_setting} ${RESULTSDIR}
		fi
		echo $test_status > ${RESULTSDIR}/test_results_report
		timestamp=`date | sed "s/ /_/g"`
		mv $run_dir/results_specjbb  ${RESULTSDIR}/results_${test_name}_${timestamp}
		process_specjbb_data $start_time $end_time 
		if [[ $to_use_pcp -eq 1 ]]; then
			stop_pcp_subset
		fi
	done
}

usage()
{
	echo "Usage $1:"
	echo "  --inc-warehouses: how many warehouses to increment each time, default"
	echo "    else increment_warehouse=echo ${end_warehouse}/8."
	echo "  --java_exec <java path>:  Path to the java to run."
	echo "  --java_version <number>: Version of java want to run, ie 21"
	echo "  --max_jvms: Runs one jvm per node."
	echo "  --node_pinning: If set to y, then will bind to the numa node, default is n."
	echo "  --nr-jvms: number of jvms to use, default 1 and the # numa nodes."
	echo "  --regression: regression runs, settings, measurement=120, total 8 warehouse data points."
	echo "  --runtime <seconds>: Seconds to run the test for."
	echo "  --specjbb_kit <specjbb kit>:  Path to the specjbb kit to use."
	echo "  --start-warehouses: Number of warehouses to start at, default 2, if cpus < 16 else value is calculated."
	echo "  --stop-warehouse: Warehouses top stop at.  Default is ncpus."
	echo "  --usage: this is usage message."
	source ${TOOLS_BIN}/general_setup --usage
}


found=0
show_usage=0
for arg in "$@"; do
	if [ $found -eq 1 ]; then
		tools_git=$arg
		found=0
	fi
	if [[ $arg == "--tools_git" ]]; then
		found=1
	fi

	#
	# We do the usage check here, as we do not want to be calling
	# the common parsers then checking for usage here.  Doing so will
	# result in the script exiting with out giving the test options.
	#
	if [[ $arg == "--usage" ]]; then
		show_usage=1
	fi
done

#
# Check to see if the test tools directory exists.  If it does, we do not need to
# clone the repo.
#
TOOLS_BIN=${HOME}/test_tools
export TOOLS_BIN
if [ ! -d "${TOOLS_BIN}" ]; then
	git clone $tools_git ${TOOLS_BIN}
	if [ $? -ne 0 ]; then
		error_out "pulling git $tools_git failed." 1
	fi
fi

if [ $show_usage -eq 1 ]; then
	usage $0
fi

source ${TOOLS_BIN}/general_setup "$@"
# Gather hardware information
${TOOLS_BIN}/gather_data ${curdir}


#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#


ARGUMENT_LIST=(
	"inc-warehouses"
	"iterations"
	"java_version"
	"max_jvms"
	"nr-jvms"
	"node_pinning"
	"java_exec"
	"runtime"
	"specjbb_kit"
	"start-warehouses"
	"stop-warehouses"
)

NO_ARGUMENTS=(
	"regression"
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

#
# Verify there were no errors
#
if [ $? -ne 0 ]; then
	error_out "Failed: parsing arguments." 1
fi

eval set --$opts
#
# Determine how many numa nodes we have.
# We will run on each node.  If regression is designated we will
# run on 1 node and the maximum number of nodes.
#
numb_nodes=$(ls -1d /sys/devices/system/node/node* | wc -l)

while [[ $# -gt 0 ]]; do
	case "$1" in
		--inc-warehouses)
			increment_warehouse=$2
			shift 2
		;;
		--java_version)
			java_version=$2
			shift 2
		;;
		--max_jvms)
			nr_jvms=$numb_nodes
			shift 1
		;;
		--node_pinning)
			node_pinning=$2
			shift 2
		;;
		--nr-jvms)
			node_list=$2
			shift 2
		;;
		--java_exec)
			java_exec=$2
			shift 2
		;;
		--regression)
			regression=1
			shift 1
		;;
		--runtime)
			runtime=$2
			shift 2
		;;
		--specjbb_kit)
			specjbb_kit=$2
			shift 2
		;;
		--start-warehouses)
			start_warehouse=$2
			shift 2
		;;
		--stop-warehouses)
			end_warehouse=$2
			shift 2
		;;
		-h)
			usage $0
		;;
		--)
			break;
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

if [[ ! -f ${run_dir}/specjbb.json ]]; then
	error_out "Package definition file ${run_dir}/specjbb.json  is missing."
fi
${TOOLS_BIN}/package_tool --wrapper_config ${run_dir}/specjbb.json --no_packages $to_no_pkg_install
if [[ $? -ne 0 ]]; then
	error_out "Package installation of ${run_dir}/specjbb.json  using ${TOOLS_BIN}/package_tool was unsuccessful."
fi
if [[ ! -f ${run_dir}/specjbb_${java_version}.json ]]; then
	error_out "Package definition file ${run_dir}/specjbb_${java_version}.json  is missing.  Is the package file for $java_version defined?" 1
fi
${TOOLS_BIN}/package_tool --wrapper_config ${run_dir}/specjbb_${java_version}.json --no_packages $to_no_pkg_install
if [[ $? -ne 0 ]]; then
	error_out "Package installation of ${run_dir}/specjbb_${java_version}.json  using ${TOOLS_BIN}/package_tool was unsuccessful."
fi

#
# Ubuntu is different on where it places the java.
# The version is not linked out of alternative, just the default, and
# it uses the name of arch.
#
os=`${TOOLS_BIN}/detect_os`
if [[ $os == "ubuntu" ]]; then
	java_exec="/usr/lib/jvm/java-${java_version}-openjdk-*/bin/java"
else
	java_exec="/etc/alternatives/jre_"${java_version}"/bin/java"
fi
#
# How many cpus in the system
#
wcpus=`cat /proc/cpuinfo | grep processor | wc -l`
wcpus=`echo "${wcpus}*2" | bc`

#
# Setup the default warehouses and increments.
#
end_warehouse=$wcpus
if [[ $start_warehouse -eq 0 ]]; then
	if [ $wcpus -gt 16 ]; then
		increment_warehouse=`echo "${end_warehouse}/8" | bc`
		start_warehouse=`echo "(${end_warehouse}-(${increment_warehouse}*8))+${increment_warehouse}" | bc`
	else
		start_warehouse=2
		increment_warehouse=2
	fi
fi

if [ $numb_nodes -eq 1 ]; then
	nodes="1"
else
	nodes=`echo ${node_list} | sed "s/,/ /g"`
fi
pushd /$to_home_root/$to_user/uploads > /dev/null
if [[ ${specjbb_kit} == "" ]]; then
	specjbb_kit=`ls -rt SPECjbb2005_kit* | tail -1`
	if [[ $specjbb_kit == *"tar.gz" ]]; then
		tar xf $specjbb_kit
		specjbb_kit=`ls -rt SPECjbb2005_kit* | tail -1`
	fi
fi
popd > /dev/null
pushd $run_dir > /dev/null
cd ..
tar xf /$to_home_root/$to_user/uploads/$specjbb_kit
if [[ ! -d specjbb ]]; then
	mkdir specjbb
fi
cd specjbb
tar xf /$to_home_root/$to_user/uploads/$specjbb_kit
cp -R SPECjbb2005/* .
popd > /dev/null

if [ $regression -eq 1 ]; then
	nodes="1 ${numb_nodes}"
fi

#
# Iterate over the nodes
#
if [[ $to_use_pcp -eq 1 ]]; then
	source $TOOLS_BIN/pcp/pcp_commands.inc
	setup_pcp
	pcp_cfg=$TOOLS_BIN/pcp/default.cfg
	#
	# Set the pcp file and include the number of jvm nodes doing.
	#
	pcp_out=specjbb_jvms_${node_jvms}
	#
	# Only set this once.  We want all the pcp files in one directory.
	#
	if [[ $pdir == "" ]]; then
		pdir=/tmp/pcp_`date "+%Y.%m.%d-%H.%M.%S"`
	fi
	start_pcp ${pdir}/ $pcp_out $pcp_cfg
fi

for entry in $nodes; do
	#
	# Node determination
	#
	if [ "${entry}" == "node" ]; then
		nr_jvms=$numb_nodes
	else
		nr_jvms=$entry
	fi
	node_jvms=$nr_jvms

	if [ $nr_jvms -gt $numb_nodes ]; then
		echo Error: number of nodes requested, $nr_jvms is greater then the number nodes in the system $numb_nodes
		echo skipping node $numb_nodes
		continue
	fi

	if [[ $node_pinning == "y" ]]; then
		obtain_nodes
	fi

	run_specjbb
done
if [[ $to_use_pcp -eq 1 ]]; then
	stop_pcp
	shutdown_pcp
	cp -R $pdir /tmp/${RESULTSDIR_TOP}
fi
if [[ $rtc -eq 0 ]]; then
	${TOOLS_BIN}/csv_to_json $to_json_flags --csv_file $save_csv_file --output_file results_specjbb.json
	$TOOLS_BIN/verify_results $to_verify_flags --schema_file $script_dir/results_schema.py --class_name Specjbb_Results --file results_specjbb.json
	rtc=$?
	${TOOLS_BIN}/save_results --curdir $curdir --home_root $to_home_root --copy_dir /tmp/${RESULTSDIR_TOP} --test_name $test_name --tuned_setting=$to_tuned_setting --version NONE --user $to_user
fi
exit $rtc
