#!/bin/bash
#                         License
#
# Copyright (C) 2021  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
#
# specjbb-run script automates the specjbb-run based on system size.  It does not
# include the actual specjbb kit, that is left to the end user to provide.
#
# Defined options
#
rtc=0
arguments="$@"
test_name="specjbb"
version="1.0"
ramp_up=60
runtime=120
measurement=60
node_pinning="no_pin"
node_list="1,node"
nr_jvms=0
specjbb_opts="none"
execname=$0
regression=0
use_pbench_version=0
specjbb_kit=""
java_exec="/bin/java"
test_status="Ran"
RESULTSDIR=""

tools_git=https://github.com/redhat-performance/test_tools-wrappers

if [ ! -f "/tmp/${test_name}.out" ]; then
	command="${0} $@"
	echo $command
	$command &> /tmp/${test_name}.out
	rtc=$?
	if [[ -f /tmp/${test_name}.out ]]; then
		cat /tmp/${test_name}.out
		rm -f /tmp/${test_name}.out
	fi
	exit $?
fi

#
# Get the directory were the command lives.
#
curdir=`pwd`
if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi

#
# Final results are saved in ~/export_results, in timestamp directories.
#
rm -rf $run_dir/results_specjbb_*

error_out()
{
	echo $1
	exit $2
}

#
# How many cpus in the system
#
wcpus=`cat /proc/cpuinfo | grep processor | wc -l`
wcpus=`echo "${wcpus}*2" | bc`

# Gather hardware information
${curdir}/test_tools/gather_data ${curdir}

#
# Setup the default warehouses and increments.
#
end_warehouse=$wcpus
if [ $wcpus -gt 16 ]; then
	increment_warehouse=`echo "${end_warehouse}/8" | bc`
	start_warehouse=`echo "(${end_warehouse}-(${increment_warehouse}*8))+${increment_warehouse}" | bc`
else
	start_warehouse=2
	increment_warehouse=2
fi

#
# Reduce the data.  We take the max for each warehouse
#
process_specjbb_data()
{
	total_data=$(mktemp /tmp/specjbb_data.XXXXXX)
	pushd $run_dir > /dev/null
	#
	# results_specjbb_jvms* is a formatted directory name.
	#   Field separator is a '_'
	#   Last field is the node pinning status.
	#   Third field from the end is the number of jvms.
	#
	for run in `ls -d results_specjbb_jvms*`; do
		run=`echo $run | sed "s/://g"`
		if [[ ! -d $run ]]; then
			continue
		fi
		pushd $run/SPECjbbSingleJVM > /dev/null
		njvms=`echo $run | rev | cut -d_ -f3 | rev`
		node_pin=`echo $run | rev | cut -d_ -f1 | rev`
		[ -n "njvms" ] && [ "$njvms" -eq "$njvms" ] 2>/dev/null
		if [[ $? -ne 0 ]]; then
			popd > /dev/null
			continue;
		fi
		csv_file=results_${test_name}.csv
		rm -f $csv_file
		rm -f $total_data
		#
		# Start with the test metadata header.
		#
 		$TOOLS_BIN/test_header_info --front_matter --results_file $csv_file --host $to_configuration --sys_type $to_sys_type --tuned $to_tuned_setting --results_version $version --test_name $test_name
		#
		# Now the specific test meta data
		#
 		$TOOLS_BIN/test_header_info --results_file $csv_file --meta_output "n_jvms: $njvms" --meta_output "numa node pin: $node_pin" 
		for file_in in `ls *txt`; do
			wh_found=0
			cat $file_in | sed "s/[*]/ /g" > ${file_in}.out
			#
			# jvm: The jvm number this data pertains to.  If node pinning is active
			#      then this is also the memory node and cpu node we are pinned to.
			#
			jvm=`echo $file_in | cut -d'.' -f2 | bc`
			echo "Warehouses:JVM $jvm BOPS" >> $csv_file
			while IFS= read -r data_in
			do
				#
				# Keep reading until Warehouses is hit.  Then keep
				# going until the new line is hit.
				#
				if [[ ${data_in} == *"Warehouses"* ]]; then
					wh_found=1;
					continue
				fi
				if [ $wh_found -eq 0 ]; then
					continue
				fi
				cline=`echo $data_in | sed "s/^ //"`
				#
				# End of data is indicated by an empty line.
				#
				if [[ $cline == "" ]]; then
					break
				fi
				echo $cline | sed "s/ /:/g" >>  $total_data
				echo $cline | sed "s/ /:/g" >> $csv_file
			done < "${file_in}.out"
			echo "" >> $csv_file
		done
		#
		#  Now lets sum up all the jvms.  We sort the $total_data file numerically.
		#  This puts the file in ascending warehouse order.
		#
		sort -n $total_data > ${total_data}_sorted
		start_diff=0
		last_wh=0
		sum=0

		echo "Warehouses:Total BOPS" >>$csv_file
		while IFS= read -r data_in
		do
			cur_chk=`echo $data_in | cut -d: -f1`
			value=`echo $data_in | cut -d: -f2`
			#
			# If we are the first line being read.
			#
			if [ $start_diff -eq 0 ]; then
				start_diff=1
				last_wh=$cur_chk
				sum=$value
				last_line=$data_in
				continue
			fi
			#
			# If the prior wh does not match the current wh report the sum.
			#
			if [ $last_wh != $cur_chk ]; then
				echo $last_wh:$sum>> $csv_file
				sum=$value
				last_wh=$cur_chk
				continue;
			fi
			let "sum=$sum+$value"
		done < "${total_data}_sorted"
		#
		# Do not forget the last line.
		#
		echo $last_wh:$sum >> $csv_file
		lines=`wc -l $csv_file | cut -d' ' -f 1`
		if [ $lines -lt 2 ]; then
			test_status="Failed"
			rtc=1
		fi
		popd > /dev/null
		cp -R $run $RESULTSDIR
	done
	#
	# Remove he temporary files.
	#
	rm -f $total_data ${total_data}_sorted
}

#
# Populate the property file with the appropriate information.
#
set_prop_file()
{
	#
	# syntax of $1
	# ENDWH=<val>:STARTWH=<val> and so forth.
	#
	if [[ $1 != "none" ]]; then
		config_list=`echo $1 | cut -d: -f 2-`
		work_with=`echo $config_list | sed "s/:/ /g"`
		for i in $work_with; do
			field=`echo $i | cut -d'=' -f 1`
			value=`echo $i | cut -d'=' -f 2`

			if [[ $field == "ENDWH" ]]; then
				end_warehouse=$value
				continue
			fi
			if [[ $field == "INCWH" ]]; then
				increment_warehouse=$value
				continue
			fi
			if [[ $field == "STARTWH" ]]; then
				start_warehouse=$value
				continue
			fi
			if [[ $field == "RAMPUP_TIME" ]]; then
				ramp_up=$value
				continue
			fi
			if [[ $field == "MEASURE_TIME" ]]; then
				measurement=$value
				continue
			fi
		done
	fi
	if [ $regression -eq 1 ]; then
		measurement=120
		increment_by=`echo "${end_warehouse}/8" | bc`
		increment_warehouse=$increment_by

	fi
	sed "s/input.ramp_up_seconds=30/input.ramp_up_seconds=${ramp_up}/g" $run_dir/SPECjbb.props > /tmp/temp
	sed "s/input.measurement_seconds=240/input.measurement_seconds=${measurement}/g" /tmp/temp > /tmp/temp1
	sed "s/#input.ending_number_warehouses=2/input.ending_number_warehouses=${end_warehouse}/g" /tmp/temp1 > /tmp/temp
	sed "s/input.starting_number_warehouses=1/input.starting_number_warehouses=${start_warehouse}/g" /tmp/temp > /tmp/temp1
	sed "s/input.output_directory=results/input.output_directory=results_specjbb/g" /tmp/temp1 > /tmp/temp
	sed "s/input.increment_number_warehouses=1/input.increment_number_warehouses=${increment_warehouse}/g" /tmp/temp > $run_dir/prop.file
}

#
# Execute specjbb.  Passed in is 
#  syntax of $1
#  ENDWH=<val>:STARTWH=<val> and so forth.
#
execute_specjbb()
{
	declare -a pids
	pindex=0
	set_prop_file $1

	np_status=""
	for pinning in $node_pinning; do
		jvm_index=0
		#
		# Start the required number of jvms
		#
		for jvms in 0 `seq 1 1  $nr_jvms`; do
			#
			# Actual jvms is $jvms+1
			#
			let "jvm_index=$jvms+1"
			if [[ $pinning == "pin" ]]; then
				#
				# One JVM group per numa node.
				#
				echo numactl  --membind  $jvms --cpunodebind $jvms  ./run.sh $java_exec
				np_status="y"
				numactl  --membind  $jvms --cpunodebind $jvms ./run.sh $java_exec >> /tmp/${test_name}_${to_tuned_setting}_job_${jvm_index}_of_$nr_jvms_np_y.out &
				if [ $? -ne 0 ]; then
					#
					# Fatal error, bail out.
					#
					error_out "Error: numactl failed" 1
				fi
			else
				np_status="n"
				./run.sh $java_exec >> /tmp/${test_name}_${to_tuned_setting}_job_${jvm_index}_$nr_jvms.out &
			fi
			#
			# Save the pid for later waiting.
			#
			pids[${pindex}]=$!
			let "pindex=$pindex+1"
		done
		#
		# Wait for all the  jvms to finish.
		#
		for pid in ${pids[*]}; do
			wait $pid
			if [ $? -ne 0 ]; then
				rtc=1
			fi
		done
		if [ $rtc -ne 0 ]; then
			error_out "Error: One or more specjbb jobs failed" 1
		fi
		#
		# At this point $jvm_index is the number of jvms we ran with.
		#
		mv $run_dir/results_specjbb $run_dir/results_specjbb_jvms_${jvm_index}_np_${np_status}
	done
}

#
# Run the specjbb benchmark
#
run_specjbb()
{

	#
	# Prepare things for execution.
	#
	cp $run_dir/specjbb_extra/run.sh $run_dir
	cd $run_dir

	#
	# Prepare things for execution.
	#
	file=`/$to_home_root/$to_user/tools_bin/get_params_file -d /$to_home_root/$to_user -c ${to_sysname} -t ${test_name}`

	# Arrays are 0 based
	let nr_jvms="$nr_jvms-1"
	for iterations  in 1 `seq 2 1 $to_times_to_run`; do
		pindex=0
		if test -f "$file"; then
			while IFS= read -r specjbb_opts
			do
				execute_specjbb $specjbb_opts
			done < "$file"
		else
			execute_specjbb $specjbb_opts
		fi
	done

#
# We need to process the data 
#
	RESULTSDIR=$run_dir/results_${test_name}_${to_tuned_setting}
	#
	# We do not want any old data.
	#
	rm -rf ${RESULTSDIR}
	mkdir -p $RESULTSDIR
	pushd $run_dir > /dev/null
	process_specjbb_data
	#
	# Save the results.
	#
	${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --copy_dir ${RESULTSDIR} --test_name $test_name --tuned_setting=$to_tuned_setting --version NONE --user $to_user
	popd > /dev/null
}

#
# Run the test via pbench.
#
run_pbench_pbench_specjbb()
{
	cd /usr/local/share/
	tar xvf  $to_home_root/$to_user/uploads/$specjbb_kit
	ln -s SPECjbb2005 specjbb2005
	pbench-specjbb2005 --heap-size=8192m --nr-jvms=$nr_jvms --start-warehouses=$start_warehouse --inc-warehouse=$increment_warehouse --runtime=$runtime --stop-warehouses=$end_warehouse
	results_prefix=$to_puser"_instance_"$to_configuration
	for specdir in `ls -d /var/lib/pbench-agent/specjbb2005*`; do
		pushd /tmp > /dev/null
		RESULTSDIR=results_${test_name}_${tuned_setting}_$(date "+%Y.%m.%d-%H.%M.%S")
		mkdir -p ${RESULTSDIR}
		rm -rf results_${test_name}_${to_tuned_setting} 
		cp -R ${RESULTSDIR} results_${test_name}_${to_tuned_setting} 
		timestamp=`date | sed "s/ /_/g"`
		
		cp -R $specdir/results results_${test_name}_${to_tuned_setting}
		mv results_${test_name}_${to_tuned_setting}/results results_${test_name}_${to_tuned_setting}/results_${test_name}_${timestamp}

		#
		# Now handle the results file for the pbench run
		#
		process_specjbb_data
		echo $test_status > results_${test_name}_${to_tuned_setting}/test_results_report
		tar hcf results_pbench_${test_name}_${to_tuned_setting}.tar results_${test_name}_${to_tuned_setting}
		${curdir}/test_tools/save_results --curdir $curdir --home_root $to_home_root --copy_dir /tmp/${RESULTSDIR} --test_name $test_name --tuned_setting=$to_tuned_setting --version NONE --user $to_user
		popd > /dev/null
	done
	value=`$TOOLS_BIN/set_pbench_variables --host_config $to_configuration --sys_type $to_sys_type --test ${test_name} --pbench_user $to_puser --run_label $to_run_label`
	hostname=`echo $value | cut -d: -f 1| sed "s/${to_puser}_//g"`

	export hostname
	results_prefix=`echo $value | cut -d: -f 2`

	echo $TOOLS_BIN/pbench_copy_data --hostname "${to_puser}_${to_run_label}" --user "${to_puser}" --prefix ${results_prefix}
	$TOOLS_BIN/pbench_copy_data --hostname "${to_puser}_${to_run_label}" --user "${to_puser}" --prefix ${results_prefix}
}

#
# Run specjbb via execute_pbench
#
run_specjbb_via_pbench()
{
	cd ${curdir}
	$TOOLS_BIN/execute_via_pbench --cmd_executing "$0" $arguments --test $test_name --spacing 11 --pbench_stats $to_pstats
	rtc=$?
}

usage()
{
	echo "Usage $1:"
	echo "  --inc-warehouses: how many warehouses to increment each time, default"
	echo "    else increment_warehouse=echo ${end_warehouse}/8."
	echo "  --java_exec <java path>:  Path to the java to run.  Non-pbench version only."
	echo "  --max_jvms: Runs one jvm per node."
	echo "  --node_pinning <request>: Tells to bind jvm to a node or not"
	echo "    If we are binding, we will bind one set of jvms per node."
	echo "    Request:"
	echo "      pin: then will bind the jvm to a numa node."
	echo "      no_pin: then will not pin the jvms"
	echo "      pin,no_pin: Will do both nopinning and pinning of jvms"
	echo "  --nr-jvms: number of jvms to use, default 1 and the # numa nodes."
	echo "  --regression: regression runs, settings, measurement=120, total 8 warehouse data points."
	echo "  --runtime <seconds>: Seconds to run the test for (pbench version only)."
	echo "  --specjbb_kit <specjbb kit>:  Path to the specjbb kit to use."
	echo "  --start-warehouses: Number of warehouses to start at, default 2, if cpus < 16 else value is calculated."
	echo "  --stop-warehouse: Warehouses top stop at.  Default is ncpus."
	echo "  --usage: this is usage message."
	echo "  --use_pbench_version: Instead of running the wrappers version."
	echo "    of specjbb, use pbench-specjbb when pbench is requested."
	source test_tools/general_setup --usage
}


found=0
show_usage=0
for arg in "$@"; do
	if [ $found -eq 1 ]; then
		tools_git=$arg
		found=0
	fi
	if [[ $arg == "--tools_git" ]]; then
		found=1
	fi

	#
	# We do the usage check here, as we do not want to be calling
	# the common parsers then checking for usage here.  Doing so will
	# result in the script exiting with out giving the test options.
	#
	if [[ $arg == "--usage" ]]; then
		show_usage=1
	fi
done

#
# Check to see if the test tools directory exists.  If it does, we do not need to
# clone the repo.
#
if [ ! -d "${curdir}/test_tools" ]; then
	git clone $tools_git ${curdir}/test_tools
	if [ $? -ne 0 ]; then
		error_out "pulling git $tools_git failed." 1
	fi
fi

if [ $show_usage -eq 1 ]; then
	usage $0
fi

# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_pbench: Run the test via pbench
# to_puser: User running pbench
# to_run_label: Label for the run
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

pushd $curdir > /dev/null
source test_tools/general_setup "$@"
popd > /dev/null

ARGUMENT_LIST=(
	"inc-warehouses"
	"iterations"
	"max_jvms"
	"nr-jvms"
	"node_pinning"
	"java_exec"
	"runtime"
	"specjbb_kit"
	"start-warehouses"
	"stop-warehouses"
)

NO_ARGUMENTS=(
	"regression"
	"use_pbench_version"
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

#
# Verify there were no errors
#
if [ $? -ne 0 ]; then
	error_out "Failed: parsing arguments." 1
fi

numb_nodes=`$TOOLS_BIN/detect_numa`
eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--inc-warehouses)
			increment_warehouse=$2
			shift 2
		;;
		--max_jvms)
			nr_jvms=$numb_nodes
			shift 1
		;;
		--node_pinning)
			node_pinning=`echo $2 | sed "s/,/ /g"`
			shift 2
		;;
		--nr-jvms)
			node_list=$2
			shift 2
		;;
		--java_exec)
			java_exec=$2
			shift 2
		;;
		--regression)
			regression=1
			shift 1
		;;
		--runtime)
			runtime=$2
			shift 2
		;;
		--specjbb_kit)
			specjbb_kit=$2
			shift 2
		;;
		--start-warehouses)
			start_warehouse=$2
			shift 2
		;;
		--stop-warehouses)
			end_warehouse=$2
			shift 2
		;;
		-h)
			usage $0
		;;
		--use_pbench_version)
			use_pbench_version=1
			shift 1
		;;
		--)
			break; 
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

if [ $numb_nodes -eq 1 ]; then
	nodes="1"
else
	nodes=`echo ${node_list} | sed "s/,/ /g"`
fi

if [[ ${specjbb_kit} == "" ]]; then
	pushd /$to_home_root/$to_user/uploads > /dev/null
	specjbb_kit=`ls -rt SPECjbb2005_kit* | tail -1`
	if [[ $specjbb_kit == *"tar.gz" ]]; then
		tar xf $specjbb_kit
		specjbb_kit=`ls -rt SPECjbb2005_kit* | tail -1`
	fi
	popd > /dev/null
fi

if  [[ ! -d $run_dir/SPECjbb2005 ]]; then
	pushd $run_dir > /dev/null
	cd ..
	tar xf /$to_home_root/$to_user/uploads/$specjbb_kit
	mkdir -p specjbb
	cd specjbb
	tar xf /$to_home_root/$to_user/uploads/$specjbb_kit
	cp -R SPECjbb2005/* .
	popd > /dev/null
fi

if [ $regression -eq 1 ]; then
	nodes="1 ${numb_nodes}"
fi

#
# Iterate over the nodes
#
for entry in $nodes; do
	#
	# Node determination
	#
	if [ "${entry}" == "node" ]; then
		nr_jvms=$numb_nodes
	else
		nr_jvms=$entry
	fi

	if [ $nr_jvms -gt $numb_nodes ]; then
		echo Error: number of nodes requested, $nr_jvms is greater then the number nodes in the system $numb_nodes
		echo skipping node $numb_nodes
		rtc=1
		continue
	fi

	if [ $to_pbench -eq 1 ]; then
		if [ $use_pbench_version -eq 1 ]; then
			run_pbench_pbench_specjbb
		else
			run_specjbb_via_pbench
		fi
	else
		run_specjbb
	fi
done
exit $rtc
